config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :wikis

  resources :charges, only: [:new, :create]

  post 'charges/downgrade'

  post 'wikis/add_collaborators'

  post 'wikis/remove_collaborators'

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  scope :visible_to, -> (user) { user && ((user.role == "admin") || (user.role == "premium")) ? all : where(private: false) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])


    if @wiki.update(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting your wiki."
      render :show
    end
  end

  def add_collaborators
    @user = User.find(params[:user_id])
    @wiki = Wiki.find(params[:id])
    if @wiki.users << @user
      flash[:notice] = "\"#{@user.email}\" is now a collaborator."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error adding a collaborator."
      render :edit
    end
  end

  def remove_collaborators
    @user = User.find(params[:user_id])
    @wiki = Wiki.find(params[:id])
    if @wiki.users.delete(@user)
      flash[:notice] = "\"#{@user.email}\" is no longer a collaborator."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error removing the collaborator."
      render :edit
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_collaborator.html.erb
<%= form_tag wikis_add_collaborators_path do %>
  <%= label_tag :add_collaborator %>
  <%= hidden_field_tag :id, @wiki.id %>
  <%= select_tag :user_id , options_from_collection_for_select(User.all, 'id', 'email') %>
  <%= submit_tag "Save", class: 'btn btn-success' %>
<% end %>

<%= form_tag wikis_remove_collaborators_path do %>
  <%= label_tag :remove_collaborator %>
  <%= hidden_field_tag :id, @wiki.id %>
  <%= select_tag :user_id , options_from_collection_for_select(@wiki.users, 'id', 'email') %>
  <%= submit_tag "Delete", class: 'btn btn-danger' %>
<% end %>

app/views/wikis/_form.html.erb
 <%= form_for @wiki do |f| %>
   <% if @wiki.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(@wiki.errors.count, "error") %>.</h4>
       <ul>
         <% @wiki.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
   <div class="form-group">
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
   </div>
   <div class="form-group">
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
   </div>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
   <% if current_user.admin? || current_user.premium? %>
     <div class="form-group">
       <%= f.label :private, class: 'checkbox' do %>
         <%= f.check_box :private %> Private wiki
       <% end %>
     </div>
   <% end %>
 <% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
</div>


<div class="col-md-8">
  <%= render partial: 'collaborator', locals: { wiki: @wiki } %>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <% if current_user.standard? && wiki.private? %>
        <% else current_user.admin? || ( current_user.premium? && (current_user == wiki.user)) %>
          <%= link_to (markdown_to_html wiki.title), wiki %>
        <% end %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>

<div class="col-md-8">
  <%= render partial: 'collaborator', locals: { wiki: @wiki } %>
</div>

app/views/wikis/show.html.erb
<h1><%= (markdown_to_html @wiki.title) %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= (markdown_to_html @wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% if policy(@wiki).destroy? %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    <% end %>
  </div>
</div>